language: java

sudo: false

script: ./mvn clean package

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - christian.mainka@hackmanit.de
